apiVersion: v1
kind: Service
metadata:
  name: {{ include "task.fullname" . }}-server
  labels:
    {{- include "task.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    {{- include "task.selectorLabels" (dict "ctx" . "component" "server") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
