//! **One authenticated dial, two transports.** What an application
//! outside this repo needs in order to reach a Task server, and nothing
//! else.
//!
//! [`task_client`](https://docs.rs/task-client) is the supported way to
//! *open an org* — session files, the embedded router, the local-first
//! fallback — and every bit of that is native. A browser app has none of
//! it and needs none of it: it holds a token its own sign-in produced,
//! and wants typed clients over a socket. That is this crate.
//!
//! ```ignore
//! let client: ProjectServiceClient =
//!     task_dial::establish_at("wss://task.example.com/org/acme/vox", Some(&token)).await?;
//! ```
//!
//! The typed clients themselves are generated by `#[architect::rpc]` and
//! carry no transport assumptions, so the client an external app holds is
//! literally the same type a plugin holds. Only the dial differs, and only
//! because browsers and native clients are handed different levers.
//!
//! # Why the identity rides the handshake
//!
//! vox middleware is per *typed client*, keyed to a service descriptor, so
//! there is no per-call choke point to hang a token on: every one of the
//! hundred-odd client constructions would have to remember, and a
//! forgotten one fails **open** and silently. One connection per endpoint
//! is the model, so the token is presented once, at establish, and the
//! server applies it to every call on that connection.
//!
//! # Why the two transports differ, and why that is not an inconsistency
//!
//! A native client controls its handshake request, so the token goes in
//! `Authorization: Bearer` — the same channel the HTTP surface already
//! accepts. A browser cannot set request headers at all, and the token
//! must not ride the URL (query strings land in every proxy and access
//! log on the path), so the **subprotocol list** is the one lever left.
//! See [`subprotocols`] and [`dial_ws_native`] for why symmetry between
//! the two is a trap rather than a tidiness.
//!
//! # Where this came from
//!
//! It was inside `task-ui-core`, a Dioxus crate, which is why the web app
//! had a working browser dial and everyone else hand-rolled one. The
//! cancel-safety in [`dial_ws`] is the part a hand-rolled version gets
//! wrong, and it is a page-killing bug when it is wrong — so it lives
//! somewhere an app can depend on without depending on a UI framework.

/// The subprotocol every dial offers and the server selects.
///
/// Offering any subprotocol makes the server's echo mandatory, which is
/// what lets the bearer subprotocol be added without breaking the
/// handshake. Mirrors `task_server::VOX_SUBPROTOCOL` — stated here rather
/// than imported, because a client must not depend on the server crate.
pub const VOX_SUBPROTOCOL: &str = "vox.v1";

/// Prefix of the subprotocol carrying the session token
/// (`task_server::VOX_BEARER_SUBPROTOCOL_PREFIX`).
pub const VOX_BEARER_SUBPROTOCOL_PREFIX: &str = "vox.bearer.";

/// Establish a client of type `C` against `url`, presenting `bearer` at
/// the handshake.
///
/// No caching and no retry: this is the dial itself, and what to do about
/// a dead connection is the caller's policy. (`task-ui-core` caches one
/// root per endpoint and revalidates it; a CLI dials per command.)
///
/// # Errors
///
/// The dial or the vox handshake failing, as a message — a browser gives
/// an opaque `Event` for a failed socket, so there is no error type worth
/// preserving underneath.
pub async fn establish_at<C>(url: &str, bearer: Option<&str>) -> Result<C, String>
where
    C: vox_core::FromVoxLane + 'static,
{
    if url.is_empty() {
        return Err("no vox URL given".to_owned());
    }
    #[cfg(target_arch = "wasm32")]
    let link = dial_ws(url, bearer).await?;
    #[cfg(not(target_arch = "wasm32"))]
    let link = dial_ws_native(url, bearer).await?;
    vox_core::initiator_on(link)
        .establish::<C>()
        .await
        .map_err(|e| format!("establish `{url}`: {e:?}"))
}

/// The subprotocol list a browser dial offers: always [`VOX_SUBPROTOCOL`],
/// plus `vox.bearer.<token>` when signed in.
///
/// Session tokens are base64url-no-pad, and the issuer's redirect-flow
/// tokens are JWT-shaped (base64url segments joined by `.`); both fit the
/// RFC 7230 token charset a subprotocol value must use, so no extra
/// encoding is needed. The dot matters: it was being dropped once, and a
/// person who signed in through the issuer's redirect then dialled every
/// socket anonymously and saw "not a member" on every screen. A token
/// containing anything outside that charset is still dropped rather than
/// sent as a malformed header that would fail the whole handshake.
///
/// Browser-only: native presents the identity as an `Authorization`
/// header instead (see [`dial_ws_native`]). Compiled natively too, so the
/// unit tests below can run.
#[must_use]
pub fn subprotocols(bearer: Option<&str>) -> Vec<String> {
    let mut protos = vec![VOX_SUBPROTOCOL.to_owned()];
    if let Some(token) = bearer.filter(|t| {
        !t.is_empty()
            && t.bytes()
                .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'-' | b'_' | b'.' | b'~'))
    }) {
        protos.push(format!("{VOX_BEARER_SUBPROTOCOL_PREFIX}{token}"));
    }
    protos
}

/// Native dial: the token goes in a plain `Authorization: Bearer` header.
///
/// Replaces `WsLink::connect`, which takes only a URL, by building the
/// same `tokio_tungstenite` stream and handing it to the public
/// `WsLink::new`.
///
/// # Why native offers NO subprotocol
///
/// Symmetry with the browser dial would be nice, and costs an outage.
/// tungstenite is stricter than RFC 6455 here: the spec lets a server that
/// selects no subprotocol simply omit the response header (§4.2.2, and
/// browsers accept that), but tungstenite treats "I offered, you didn't
/// echo" as a **handshake failure** (`SubProtocolError::NoSubProtocol`).
/// So a native client offering `vox.bearer.…` cannot talk to any peer that
/// does not echo it — an older task-server, or an ingress that drops the
/// header. `Authorization` needs no negotiation and has none of that
/// coupling.
///
/// **`wss://` callers must install a rustls `CryptoProvider` first.** A
/// binary whose graph unifies both `ring` and `aws-lc-rs` leaves rustls
/// unable to choose, and the failure surfaces here as an opaque connect
/// error.
///
/// # Errors
///
/// An unrepresentable URL, or the connection failing.
#[cfg(not(target_arch = "wasm32"))]
pub async fn dial_ws_native(
    url: &str,
    bearer: Option<&str>,
) -> Result<vox_websocket::WsLink<tokio_tungstenite::MaybeTlsStream<tokio::net::TcpStream>>, String>
{
    use tokio_tungstenite::tungstenite::client::IntoClientRequest as _;

    let mut request = url
        .into_client_request()
        .map_err(|e| format!("ws request `{url}`: {e:?}"))?;
    if let Some(token) = bearer.filter(|t| !t.is_empty())
        && let Ok(value) = format!("Bearer {token}").parse()
    {
        request.headers_mut().insert("authorization", value);
    }
    let (stream, _response) = tokio_tungstenite::connect_async(request)
        .await
        .map_err(|e| format!("ws connect `{url}`: {e:?}"))?;
    Ok(vox_websocket::WsLink::new(stream))
}

/// Cancel-safe browser WebSocket dial (wasm replacement for
/// `vox_websocket::WsLink::connect`).
///
/// `WsLink::connect`'s dial phase is not cancel-safe: it attaches
/// `onopen`/`onerror` wasm-bindgen closures to the connecting socket and
/// only detaches them on the *success* path. On the error path — and,
/// worse, when the connect **future is dropped mid-dial**, which a UI
/// supervisor restarting on a signal change does routinely — the closures
/// drop while still attached to a socket that has not finished failing.
/// The browser then delivers the socket's `error`/`close` event into the
/// freed closure, surfacing as an uncaught `closure invoked recursively or
/// after being dropped` and a dead page.
///
/// This dial keeps the connect-phase closures in a guard whose `Drop`
/// **detaches them from the socket first** (and closes a socket being
/// abandoned), so no event can reach a dropped closure — drop order inside
/// one synchronous Rust drop cannot be interleaved with browser event
/// dispatch. On success the guard detaches and hands the open socket to
/// `WsLink::new`, which installs the steady-state handlers it owns.
///
/// # Errors
///
/// The socket failing to open, closing during the open, or the dial being
/// cancelled.
#[cfg(target_arch = "wasm32")]
pub async fn dial_ws(url: &str, bearer: Option<&str>) -> Result<vox_websocket::WsLink, String> {
    use std::cell::RefCell;
    use std::rc::Rc;

    use wasm_bindgen::JsCast;
    use wasm_bindgen::closure::Closure;

    /// Connect-phase state: the socket plus its temporary handlers.
    /// Detaches the handlers before the closure fields drop; closes the
    /// socket unless the dial completed and ownership moved to `WsLink`.
    struct Dial {
        ws: web_sys::WebSocket,
        _onopen: Closure<dyn FnMut()>,
        _onerror: Closure<dyn FnMut(web_sys::Event)>,
        _onclose: Closure<dyn FnMut(web_sys::CloseEvent)>,
        keep_open: bool,
    }
    impl Drop for Dial {
        fn drop(&mut self) {
            // Detach FIRST — after these lines the browser holds no
            // reference into the closures, so dropping them (field drop,
            // right after this body) is always safe.
            self.ws.set_onopen(None);
            self.ws.set_onerror(None);
            self.ws.set_onclose(None);
            if !self.keep_open {
                // Abandoned dial (error or caller cancellation): tear the
                // socket down so it does not keep connecting in the void.
                let _ = self.ws.close();
            }
        }
    }

    // The browser's ONE lever on a WebSocket handshake: it cannot set
    // request headers, and the token must not ride the URL, so the
    // subprotocol list is where identity goes (see `subprotocols`).
    let protocols = js_sys::Array::new();
    for proto in subprotocols(bearer) {
        protocols.push(&wasm_bindgen::JsValue::from_str(&proto));
    }
    let ws = web_sys::WebSocket::new_with_str_sequence(url, &protocols)
        .map_err(|e| format!("WebSocket::new `{url}`: {e:?}"))?;
    ws.set_binary_type(web_sys::BinaryType::Arraybuffer);

    let (tx, rx) = futures_channel::oneshot::channel::<Result<(), String>>();
    let tx = Rc::new(RefCell::new(Some(tx)));

    // FnMut (not `Closure::once`) so a stray double-fire cannot trip
    // wasm-bindgen's invoked-after-consumed check; the oneshot's take()
    // makes later fires no-ops.
    let tx_open = Rc::clone(&tx);
    let onopen = Closure::wrap(Box::new(move || {
        if let Some(tx) = tx_open.borrow_mut().take() {
            let _ = tx.send(Ok(()));
        }
    }) as Box<dyn FnMut()>);
    let tx_error = Rc::clone(&tx);
    let err_url = url.to_owned();
    let onerror = Closure::wrap(Box::new(move |_: web_sys::Event| {
        if let Some(tx) = tx_error.borrow_mut().take() {
            let _ = tx.send(Err(format!("WebSocket open failed: `{err_url}`")));
        }
    }) as Box<dyn FnMut(web_sys::Event)>);
    // `close` can arrive without a preceding `error` (a clean rejection);
    // without this handler such a dial would hang forever.
    let tx_close = Rc::clone(&tx);
    let close_url = url.to_owned();
    let onclose = Closure::wrap(Box::new(move |e: web_sys::CloseEvent| {
        if let Some(tx) = tx_close.borrow_mut().take() {
            let _ = tx.send(Err(format!(
                "WebSocket closed during open: `{close_url}` (code {})",
                e.code()
            )));
        }
    }) as Box<dyn FnMut(web_sys::CloseEvent)>);

    ws.set_onopen(Some(onopen.as_ref().unchecked_ref()));
    ws.set_onerror(Some(onerror.as_ref().unchecked_ref()));
    ws.set_onclose(Some(onclose.as_ref().unchecked_ref()));

    let mut dial = Dial {
        ws,
        _onopen: onopen,
        _onerror: onerror,
        _onclose: onclose,
        keep_open: false,
    };

    // Cancellation-safe await: dropping this future drops `dial`, whose
    // Drop detaches the handlers and closes the half-open socket.
    rx.await.map_err(|_| "dial cancelled".to_owned())??;

    // Success: keep the socket, detach the connect-phase handlers (the
    // guard's Drop), and let WsLink install its own.
    dial.keep_open = true;
    let ws = dial.ws.clone();
    drop(dial);
    Ok(vox_websocket::WsLink::new(ws))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_signed_out_dial_offers_only_the_vox_subprotocol() {
        assert_eq!(subprotocols(None), vec![VOX_SUBPROTOCOL.to_owned()]);
        assert_eq!(subprotocols(Some("")), vec![VOX_SUBPROTOCOL.to_owned()]);
    }

    /// The charset clause, and it is not hypothetical: an issuer token is
    /// JWT-shaped, so dropping dots meant every socket dialled anonymously
    /// and every screen said "not a member".
    #[test]
    fn a_jwt_shaped_token_survives_the_subprotocol_charset() {
        let jwt = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZSJ9.sig-nature_x~y";
        assert_eq!(
            subprotocols(Some(jwt)),
            vec![
                VOX_SUBPROTOCOL.to_owned(),
                format!("{VOX_BEARER_SUBPROTOCOL_PREFIX}{jwt}")
            ]
        );
    }

    /// Anything outside the charset is dropped rather than sent: a
    /// malformed subprotocol value fails the *whole* handshake, so a
    /// broken token would cost the connection rather than the identity.
    #[test]
    fn a_token_outside_the_charset_is_dropped_rather_than_sent() {
        for bad in ["has space", "semi;colon", "quote\"d", "new\nline"] {
            assert_eq!(
                subprotocols(Some(bad)),
                vec![VOX_SUBPROTOCOL.to_owned()],
                "`{bad}` reached the handshake"
            );
        }
    }
}
