//! Property tests for the parsing + indexing pipeline. The
//! store rebuilds itself by walking a Maildir on disk and
//! feeding every file through `mail-parser`; the parser is
//! supposed to be lenient + non-panicking on any input, and the
//! store layer must follow suit. We hammer both paths with
//! proptest-generated bytes (totally arbitrary + RFC-shaped) so
//! a malformed-but-valid `.eml` from the wild doesn't crash the
//! sync engine.
//!
//! The contract under test:
//! - `Store::rebuild_from_disk` must NOT panic for any byte
//!   content placed under `<root>/{cur,new,tmp}/`. Files that
//!   don't look like RFC5322 are skipped (logged), not raised.
//! - Whatever envelopes are produced must serialize through the
//!   schema without integer overflow / NULL-violation / unicode
//!   sadness — i.e. `query_envelopes` must round-trip them
//!   cleanly afterwards.

use email_store::Store;
use proptest::prelude::*;

/// Random bytes — completely arbitrary, no RFC shape at all.
/// Stresses the "garbage in `new/`" path.
fn arb_garbage() -> impl Strategy<Value = Vec<u8>> {
    proptest::collection::vec(any::<u8>(), 0..2048)
}

/// RFC-shaped headers with random content. Tests that the
/// parser handles weird-but-vaguely-structured input without
/// panic + that snippets / sizes flow into the index.
fn arb_rfc_like() -> impl Strategy<Value = Vec<u8>> {
    let header_chars = "[a-zA-Z0-9 _.,@<>/!?-]{0,80}";
    (
        proptest::collection::vec(header_chars, 0..20),
        any::<u32>(),
        proptest::string::string_regex("[a-zA-Z0-9 \r\n]{0,4096}").unwrap(),
    )
        .prop_map(|(hdrs, msgid_n, body)| {
            use std::fmt::Write as _;
            let mut out = String::new();
            for h in hdrs {
                // 50/50 the line has a colon (real header) or
                // not (folded continuation).
                if msgid_n & 1 == 0 {
                    write!(&mut out, "X-Test: {h}\r").unwrap();
                    out.push('\n');
                } else {
                    write!(&mut out, "{h}\r").unwrap();
                    out.push('\n');
                }
            }
            write!(&mut out, "Message-ID: <{msgid_n}@p.test>\r").unwrap();
            out.push('\n');
            write!(&mut out, "Subject: prop test {msgid_n}\r").unwrap();
            out.push('\n');
            out.push_str("\r\n");
            out.push_str(&body);
            out.into_bytes()
        })
}

fn write_maildir(root: &std::path::Path, files: &[Vec<u8>]) {
    for sub in ["cur", "new", "tmp"] {
        std::fs::create_dir_all(root.join(sub)).unwrap();
    }
    for (i, bytes) in files.iter().enumerate() {
        // Half the files go into new/, half into cur/ with a
        // `:2,S` info section so we exercise both flag paths.
        let (sub, name) = if i % 2 == 0 {
            ("new", format!("{i:020}.M.host"))
        } else {
            ("cur", format!("{i:020}.M.host:2,S"))
        };
        std::fs::write(root.join(sub).join(name), bytes).unwrap();
    }
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(64))]

    #[test]
    fn rebuild_never_panics_on_garbage(files in proptest::collection::vec(arb_garbage(), 0..20)) {
        let dir = tempfile::tempdir().unwrap();
        write_maildir(dir.path(), &files);
        let mut store = Store::open(dir.path()).unwrap();
        // The cardinal contract: this MUST NOT panic.
        let indexed = store.rebuild_from_disk().unwrap();
        // Every file either indexed or skipped — count must
        // bound by total file count.
        prop_assert!(indexed <= files.len(), "indexed {indexed} > files {}", files.len());
    }

    #[test]
    fn rebuild_handles_rfc_like_input(files in proptest::collection::vec(arb_rfc_like(), 0..20)) {
        let dir = tempfile::tempdir().unwrap();
        write_maildir(dir.path(), &files);
        let mut store = Store::open(dir.path()).unwrap();
        let indexed = store.rebuild_from_disk().unwrap();
        // RFC-shaped input should index ≥ 80% of the time.
        // Lower bound is conservative — proptest occasionally
        // produces inputs that even the lenient parser bounces.
        if files.len() >= 5 {
            let expected = (files.len() as f64 * 0.5) as usize;
            prop_assert!(
                indexed >= expected,
                "indexed {indexed} < expected {expected} of {}", files.len()
            );
        }

        // Round-trip whatever DID get indexed.
        let envs = store.query_envelopes("INBOX", u32::MAX).unwrap();
        for stored in envs {
            // Subjects must not contain interior NUL (sqlite
            // would silently truncate).
            prop_assert!(
                !stored.envelope.subject.contains('\0'),
                "interior NUL in subject: {:?}", stored.envelope.subject
            );
            prop_assert!(stored.envelope.date_ms >= 0);
        }
    }

    #[test]
    fn empty_files_are_safe(n in 0usize..30) {
        let files = vec![Vec::<u8>::new(); n];
        let dir = tempfile::tempdir().unwrap();
        write_maildir(dir.path(), &files);
        let mut store = Store::open(dir.path()).unwrap();
        let _ = store.rebuild_from_disk().unwrap();
    }

    #[test]
    fn fts5_search_never_panics_on_arbitrary_query(query in "[a-zA-Z0-9 ]{0,40}") {
        // FTS5 has its own MATCH syntax; ill-formed queries
        // raise errors rather than panic. We assert the
        // resilience-bound: any alphanumeric input either
        // searches or errors cleanly.
        let dir = tempfile::tempdir().unwrap();
        let mut store = Store::open(dir.path()).unwrap();
        let env = email_proto::Envelope {
            message_id: "<a@example.com>".into(),
            folder: "INBOX".into(),
            thread_id: None,
            subject: "Hello world".into(),
            from: vec![],
            to: vec![],
            cc: vec![],
            date_ms: 0,
            flags: vec![],
            has_attachments: false,
            size: 0,
            snippet: None,
        };
        store.upsert_envelope(&env, None, None, Some("body content")).unwrap();
        // Either an Ok with some hits, or an Err — never panic.
        let _ = store.search(&query, 10);
    }
}
