/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_webrenderer_free: (a: number, b: number) => void;
export const webrenderer_addProject: (a: number, b: number, c: number, d: number, e: number) => void;
export const webrenderer_addStemTrack: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const webrenderer_addStemTrackIn: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => void;
export const webrenderer_attachAudioSource: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const webrenderer_attachAudioSourceIn: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => void;
export const webrenderer_audioSourceCount: (a: number) => number;
export const webrenderer_detachAudioSource: (a: number, b: number, c: number) => void;
export const webrenderer_detachAudioSourceIn: (a: number, b: number, c: number, d: number, e: number) => void;
export const webrenderer_isPlaying: (a: number) => number;
export const webrenderer_new: (a: number) => number;
export const webrenderer_pathsToResolve: (a: number) => [number, number];
export const webrenderer_pause: (a: number) => void;
export const webrenderer_play: (a: number) => void;
export const webrenderer_positionSeconds: (a: number) => number;
export const webrenderer_projectGuid: (a: number) => [number, number];
export const webrenderer_render: (a: number, b: number, c: number, d: any, e: number, f: number, g: any) => void;
export const webrenderer_seekSeconds: (a: number, b: number) => void;
export const webrenderer_seekSecondsAt: (a: number, b: number, c: number) => void;
export const webrenderer_selectProject: (a: number, b: number, c: number) => void;
export const webrenderer_setTrackMute: (a: number, b: number, c: number) => void;
export const webrenderer_setTrackSolo: (a: number, b: number, c: number) => void;
export const webrenderer_setTrackVolume: (a: number, b: number, c: number) => void;
export const webrenderer_stop: (a: number) => void;
export const webrenderer_takeSources: (a: number) => [number, number];
export const webrenderer_trackCount: (a: number) => number;
export const webrenderer_trackPeaks: (a: number) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h5ca89d924f5a02f7: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h0ddf7788afd622d7: (a: number, b: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
